### PR TITLE
Declare globals as extern

### LINKED ISSUE #2: ftbfs with gcc 10
It fails to build unless I pass CPPFLAGS="-fcommon" (gcc>=10 defaults to -fno-common):
```
==> Starting build()...
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c main.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c main_menu.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c serial.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c options.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c sensors.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c trouble_code_reader.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c custom_gui.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c error_handlers.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c about.c
gcc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -c reset.c
gcc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Werror -DTERMIOS -o scantool main.o main_menu.o serial.o options.o sensors.o trouble_code_reader.o custom_gui.o error_handlers.o about.o reset.o -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/lib -lalleg -lm
/usr/bin/ld: main_menu.o:(.bss+0x58): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x0): multiple definition of `comport'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x18): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: main_menu.o:(.bss+0xc): multiple definition of `serial_timer_running'; main.o:(.bss+0xc): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x10): multiple definition of `serial_time_out'; main.o:(.bss+0x10): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x20): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x38): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x40): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x48): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x50): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: main_menu.o:(.bss+0x54): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
/usr/bin/ld: serial.o:(.bss+0x10): multiple definition of `serial_time_out'; main.o:(.bss+0x10): first defined here
/usr/bin/ld: serial.o:(.bss+0xc): multiple definition of `serial_timer_running'; main.o:(.bss+0xc): first defined here
/usr/bin/ld: serial.o:(.bss+0x0): multiple definition of `comport'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: serial.o:(.bss+0x18): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: serial.o:(.bss+0x20): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: serial.o:(.bss+0x38): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: serial.o:(.bss+0x40): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: serial.o:(.bss+0x48): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: serial.o:(.bss+0x50): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: serial.o:(.bss+0x54): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
/usr/bin/ld: serial.o:(.bss+0x58): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: options.o:(.bss+0x154): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
/usr/bin/ld: options.o:(.bss+0x150): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: options.o:(.bss+0x100): multiple definition of `comport'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: options.o:(.bss+0x148): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: options.o:(.bss+0x118): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: options.o:(.bss+0x0): multiple definition of `temp_error_buf'; main.o:(.bss+0x20): first defined here
/usr/bin/ld: options.o:(.bss+0x10c): multiple definition of `serial_timer_running'; main.o:(.bss+0xc): first defined here
/usr/bin/ld: options.o:(.bss+0x110): multiple definition of `serial_time_out'; main.o:(.bss+0x10): first defined here
/usr/bin/ld: options.o:(.bss+0x120): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: options.o:(.bss+0x138): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: options.o:(.bss+0x140): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: options.o:(.bss+0x158): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: sensors.o:(.bss+0x154): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
/usr/bin/ld: sensors.o:(.bss+0x0): multiple definition of `temp_error_buf'; main.o:(.bss+0x20): first defined here
/usr/bin/ld: sensors.o:(.bss+0x100): multiple definition of `comport'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: sensors.o:(.bss+0x158): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: sensors.o:(.bss+0x110): multiple definition of `serial_time_out'; main.o:(.bss+0x10): first defined here
/usr/bin/ld: sensors.o:(.bss+0x10c): multiple definition of `serial_timer_running'; main.o:(.bss+0xc): first defined here
/usr/bin/ld: sensors.o:(.bss+0x118): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: sensors.o:(.bss+0x120): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: sensors.o:(.bss+0x138): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: sensors.o:(.bss+0x140): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: sensors.o:(.bss+0x148): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: sensors.o:(.bss+0x150): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x118): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x138): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x100): multiple definition of `comport'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x0): multiple definition of `temp_error_buf'; main.o:(.bss+0x20): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x110): multiple definition of `serial_time_out'; main.o:(.bss+0x10): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x10c): multiple definition of `serial_timer_running'; main.o:(.bss+0xc): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x120): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x140): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x148): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x150): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x154): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
/usr/bin/ld: trouble_code_reader.o:(.bss+0x158): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: custom_gui.o:(.bss+0x0): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: custom_gui.o:(.bss+0x10): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: custom_gui.o:(.bss+0x28): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: custom_gui.o:(.bss+0x30): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: custom_gui.o:(.bss+0x38): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: custom_gui.o:(.bss+0x40): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: custom_gui.o:(.bss+0x44): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
/usr/bin/ld: custom_gui.o:(.bss+0x48): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x100): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x0): multiple definition of `temp_error_buf'; main.o:(.bss+0x20): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x110): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x128): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x130): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x138): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x140): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x144): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
/usr/bin/ld: error_handlers.o:(.bss+0x148): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: about.o:(.bss+0x18): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: about.o:(.bss+0x0): multiple definition of `comport'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: about.o:(.bss+0x10): multiple definition of `serial_time_out'; main.o:(.bss+0x10): first defined here
/usr/bin/ld: about.o:(.bss+0xc): multiple definition of `serial_timer_running'; main.o:(.bss+0xc): first defined here
/usr/bin/ld: about.o:(.bss+0x20): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: about.o:(.bss+0x38): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: about.o:(.bss+0x40): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: about.o:(.bss+0x48): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: about.o:(.bss+0x50): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: about.o:(.bss+0x54): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
/usr/bin/ld: about.o:(.bss+0x58): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: reset.o:(.bss+0xc): multiple definition of `serial_timer_running'; main.o:(.bss+0xc): first defined here
/usr/bin/ld: reset.o:(.bss+0x10): multiple definition of `serial_time_out'; main.o:(.bss+0x10): first defined here
/usr/bin/ld: reset.o:(.bss+0x58): multiple definition of `is_not_genuine_scan_tool'; main.o:(.bss+0x168): first defined here
/usr/bin/ld: reset.o:(.bss+0x0): multiple definition of `comport'; main.o:(.bss+0x0): first defined here
/usr/bin/ld: reset.o:(.bss+0x18): multiple definition of `datafile'; main.o:(.bss+0x120): first defined here
/usr/bin/ld: reset.o:(.bss+0x20): multiple definition of `log_file_name'; main.o:(.bss+0x130): first defined here
/usr/bin/ld: reset.o:(.bss+0x38): multiple definition of `code_defs_file_name'; main.o:(.bss+0x148): first defined here
/usr/bin/ld: reset.o:(.bss+0x40): multiple definition of `data_file_name'; main.o:(.bss+0x150): first defined here
/usr/bin/ld: reset.o:(.bss+0x48): multiple definition of `options_file_name'; main.o:(.bss+0x158): first defined here
/usr/bin/ld: reset.o:(.bss+0x50): multiple definition of `display_mode'; main.o:(.bss+0x160): first defined here
/usr/bin/ld: reset.o:(.bss+0x54): multiple definition of `system_of_measurements'; main.o:(.bss+0x164): first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:56: scantool] Error 1
```

### PR DESCRIPTION
**Pull request by xantares**
Closes #2

### CODE REVIEW

File: globals.c [hunk 1]
```diff
@@ -0,0 +1,18 @@
+#include "globals.h"
```
Comment (kees) [inline globals.c]: I'd like to avoid adding a .c file just for these variables. They should be distributed into their "parent" .c file (as you've done for the temp_error_buf and serial variables.

File: globals.c [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+
+int is_not_genuine_scan_tool;
```
Comment (kees) [inline globals.c]: All the logic for is_not_genuine_scan_tool should be entirely removed as a separate commit.

File: globals.c [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+
+// Options
+int system_of_measurements;
```
Comment (kees) [inline globals.c]: This should be defined in options.c

File: globals.c [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+int display_mode;
```
Comment (kees) [inline globals.c]: This should be in main.c

File: globals.c [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+// File names
+char *options_file_name;
```
Comment (kees) [inline globals.c]: This should be in options.c

File: globals.c [hunk 6]
```diff
@@ -0,0 +1,18 @@
...
+char *data_file_name;
```
Comment (kees) [inline globals.c]: This should be a local variable to main.c's init()

File: globals.c [hunk 7]
```diff
@@ -0,0 +1,18 @@
...
+char *code_defs_file_name;
```
Comment (kees) [inline globals.c]: This should be in trouble_code_reader.c

File: globals.c [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+char log_file_name[20];
```
Comment (kees) [inline globals.c]: This should be in main.c

File: globals.c [hunk 9]
```diff
@@ -0,0 +1,18 @@
...
+#ifdef LOG_COMMS
+char comm_log_file_name[20];
```
Comment (kees) [inline globals.c]: This should be in main.c

File: globals.c [hunk 10]
```diff
@@ -0,0 +1,18 @@
...
+#endif
+
+DATAFILE *datafile;
```
Comment (kees) [inline globals.c]: This should be in main_menu.c

**Review by kees — CHANGES_REQUESTED** [review]
Thanks for working on this! It looks like all of these variables should live in existing .c files (or get removed entirely).

**Comment by xantares** [comment]
ok, done

**Review by kees — APPROVED** [review]

**Review by kees — APPROVED** [review]

**Comment by kees** [comment]
Thanks very much!
